version: '3.4'

services:
  ocrservice:
    image: ocrservice
    build:
      context: ./
      dockerfile: ./ocr_service/Dockerfile
    ports:
      - 8000:8000
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672