version: '3.4'

services:
  ocrservice:
    image: ocrservice
    build:
      context: ./
      dockerfile: ./ocr_service/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq

  ocrllm-listener:
    build:
      context: ./
      dockerfile: ./llm_service/Dockerfile.rabbitmq
    depends_on:
      - rabbitmq
    restart: always
    volumes:
      - ./llm_service/.env:/app/.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672







